//база данных с товарами
export const dataInfo = `[    
  {
      "id":"101",
      "img":"img/product-box_item1.jpg",
      "img1":"img/product-box_item1-1.jpg",
      "img2":"img/product-box_item1-2.jpg",
      "img3":"img/product-box_item1-3.jpg",
      "name":"ELLERY X M'O CAPSULE",
      "text":"Known for her sculptural takes on traditional tailoring, Australian arbiter of cool Kym Ellery teams up with Moda Operandi.",
      "textProduct":"Compellingly actualize fully researched processes before proactive outsourcing. Progressively syndicate collaborative architectures before cutting-edge services. Completely visualize parallel core competencies rather than exceptional portals.",
      "price":"52.00",
      "color":"Red",
      "size":"Xl",
      "quantity":"2",
      "gender":"MEN"
  },
  {
      "id":"102",
      "img":"img/product-box_item2.jpg",
      "img1":"img/product-box_item2-1.jpg",
      "img2":"img/product-box_item2-2.jpg",
      "img3":"img/product-box_item2-3.jpg",
      "name":"ELLERY X M'O CAPSULE",
      "text":"Known for her sculptural takes on traditional tailoring, Australian arbiter of cool Kym Ellery teams up with Moda Operandi.",
      "textProduct":"Compellingly actualize fully researched processes before proactive outsourcing. Progressively syndicate collaborative architectures before cutting-edge services. Completely visualize parallel core competencies rather than exceptional portals.",
      "price":"52.00",
      "color":"Red",
      "size":"Xl",
      "quantity":"2",
      "gender":"WOMEN"
  },
  {"id":"103",
      "img":"img/product-box_item3.jpg",
      "img1":"img/product-box_item3-1.jpg",
      "img2":"img/product-box_item3-2.jpg",
      "img3":"img/product-box_item3-3.jpg",
      "name":"ELLERY X M'O CAPSULE",
      "text":"Known for her sculptural takes on traditional tailoring, Australian arbiter of cool Kym Ellery teams up with Moda Operandi.",
      "textProduct":"Compellingly actualize fully researched processes before proactive outsourcing. Progressively syndicate collaborative architectures before cutting-edge services. Completely visualize parallel core competencies rather than exceptional portals.",
      "price":"52.00",
      "color":"Red",
      "size":"Xl",
      "quantity":"2",
      "gender":"MEN"
  },
  {"id":"104",
      "img":"img/product-box_item4.jpg",
      "img1":"img/product-box_item4-1.jpg",
      "img2":"img/product-box_item4-2.jpg",
      "img3":"img/product-box_item4-3.jpg",
      "name":"ELLERY X M'O CAPSULE",
      "text":"Known for her sculptural takes on traditional tailoring, Australian arbiter of cool Kym Ellery teams up with Moda Operandi.",
      "textProduct":"Compellingly actualize fully researched processes before proactive outsourcing. Progressively syndicate collaborative architectures before cutting-edge services. Completely visualize parallel core competencies rather than exceptional portals.",
      "price":"52.00",
      "color":"Red",
      "size":"Xl",
      "quantity":"2",
      "gender":"MEN"
  },
  {"id":"105",
      "img":"img/product-box_item5.jpg",
      "img1":"img/product-box_item5-1.jpg",
      "img2":"img/product-box_item5-2.jpg",
      "img3":"img/product-box_item5-3.jpg",
      "name":"ELLERY X M'O CAPSULE",
      "text":"Known for her sculptural takes on traditional tailoring, Australian arbiter of cool Kym Ellery teams up with Moda Operandi.",
      "textProduct":"Compellingly actualize fully researched processes before proactive outsourcing. Progressively syndicate collaborative architectures before cutting-edge services. Completely visualize parallel core competencies rather than exceptional portals.",
      "price":"52.00",
      "color":"Red",
      "size":"Xl",
      "quantity":"2",
      "gender":"WOMEN"
  },
  {"id":"106",
      "img":"img/product-box_item6.jpg",
      "img1":"img/product-box_item6-1.jpg",
      "img2":"img/product-box_item6-2.jpg",
      "img3":"img/product-box_item6-3.jpg",
      "name":"ELLERY X M'O CAPSULE",
      "text":"Known for her sculptural takes on traditional tailoring, Australian arbiter of cool Kym Ellery teams up with Moda Operandi.",
      "textProduct":"Compellingly actualize fully researched processes before proactive outsourcing. Progressively syndicate collaborative architectures before cutting-edge services. Completely visualize parallel core competencies rather than exceptional portals.",
      "price":"52.00",
      "color":"Red",
      "size":"Xl",
      "quantity":"2",
      "gender":"WOMEN"
  },
  {"id":"107",
      "img":"img/product-box_item7.jpg",
      "img1":"img/product-box_item7-1.jpg",
      "img2":"img/product-box_item7-2.jpg",
      "img3":"img/product-box_item7-3.jpg",
      "name":"ELLERY X M'O CAPSULE",
      "text":"Known for her sculptural takes on traditional tailoring, Australian arbiter of cool Kym Ellery teams up with Moda Operandi.",
      "textProduct":"Compellingly actualize fully researched processes before proactive outsourcing. Progressively syndicate collaborative architectures before cutting-edge services. Completely visualize parallel core competencies rather than exceptional portals.",
      "price":"52.00",
      "color":"Red",
      "size":"Xl",
      "quantity":"2",
      "gender":"MEN"
  },
  {"id":"108",
      "img":"img/product-box_item8.jpg",
      "img1":"img/product-box_item8-1.jpg",
      "img2":"img/product-box_item8-2.jpg",
      "img3":"img/product-box_item8-3.jpg",
      "name":"ELLERY X M'O CAPSULE",
      "text":"Known for her sculptural takes on traditional tailoring, Australian arbiter of cool Kym Ellery teams up with Moda Operandi.",
      "textProduct":"Compellingly actualize fully researched processes before proactive outsourcing. Progressively syndicate collaborative architectures before cutting-edge services. Completely visualize parallel core competencies rather than exceptional portals.",
      "price":"52.00",
      "color":"Red",
      "size":"Xl",
      "quantity":"2",
      "gender":"MEN"
  },
  {"id":"109",
      "img":"img/product-box_item9.jpg",
      "img1":"img/product-box_item9-1.jpg",
      "img2":"img/product-box_item9-2.jpg",
      "img3":"img/product-box_item9-3.jpg",
      "name":"ELLERY X M'O CAPSULE",
      "text":"Known for her sculptural takes on traditional tailoring, Australian arbiter of cool Kym Ellery teams up with Moda Operandi.",
      "textProduct":"Compellingly actualize fully researched processes before proactive outsourcing. Progressively syndicate collaborative architectures before cutting-edge services. Completely visualize parallel core competencies rather than exceptional portals.",
      "price":"52.00",
      "color":"Red",
      "size":"Xl",
      "quantity":"2",
      "gender":"MEN"
  },
  {"id":"110",
      "img":"img/product-box_item10.jpg",
      "img1":"img/product-box_item10-1.jpg",
      "img2":"img/product-box_item10-2.jpg",
      "img3":"img/product-box_item10-3.jpg",
      "name":"ELLERY X M'O CAPSULE",
      "text":"Known for her sculptural takes on traditional tailoring, Australian arbiter of cool Kym Ellery teams up with Moda Operandi.",
      "textProduct":"Compellingly actualize fully researched processes before proactive outsourcing. Progressively syndicate collaborative architectures before cutting-edge services. Completely visualize parallel core competencies rather than exceptional portals.",
      "price":"52.00",
      "color":"Red",
      "size":"Xl",
      "quantity":"2",
      "gender":"MEN"
  },
  {"id":"111",
      "img":"img/product-box_item11.jpg",
      "img1":"img/product-box_item11-1.jpg",
      "img2":"img/product-box_item11-2.jpg",
      "img3":"img/product-box_item11-3.jpg",
      "name":"ELLERY X M'O CAPSULE",
      "text":"Known for her sculptural takes on traditional tailoring, Australian arbiter of cool Kym Ellery teams up with Moda Operandi.",
      "textProduct":"Compellingly actualize fully researched processes before proactive outsourcing. Progressively syndicate collaborative architectures before cutting-edge services. Completely visualize parallel core competencies rather than exceptional portals.",
      "price":"52.00",
      "color":"Red",
      "size":"Xl",
      "quantity":"2",
      "gender":"MEN"
  },
  {"id":"112",
      "img":"img/product-box_item12.jpg",
      "img1":"img/product-box_item12-1.jpg",
      "img2":"img/product-box_item12-2.jpg",
      "img3":"img/product-box_item12-3.jpg",
      "name":"ELLERY X M'O CAPSULE",
      "text":"Known for her sculptural takes on traditional tailoring, Australian arbiter of cool Kym Ellery teams up with Moda Operandi.",
      "textProduct":"Compellingly actualize fully researched processes before proactive outsourcing. Progressively syndicate collaborative architectures before cutting-edge services. Completely visualize parallel core competencies rather than exceptional portals.",
      "price":"52.00",
      "color":"Red",
      "size":"Xl",
      "quantity":"2",
      "gender":"MEN"
  },
  {"id":"113",
      "img":"img/product-box_item13.jpg",
      "img1":"img/product-box_item13-1.jpg",
      "img2":"img/product-box_item13-2.jpg",
      "img3":"img/product-box_item13-3.jpg",
      "name":"ELLERY X M'O CAPSULE",
      "text":"Known for her sculptural takes on traditional tailoring, Australian arbiter of cool Kym Ellery teams up with Moda Operandi.",
      "textProduct":"Compellingly actualize fully researched processes before proactive outsourcing. Progressively syndicate collaborative architectures before cutting-edge services. Completely visualize parallel core competencies rather than exceptional portals.",
      "price":"52.00",
      "color":"Red",
      "size":"Xl",
      "quantity":"2",
      "gender":"MEN"
  },
  {"id":"114",
      "img":"img/product-box_item14.jpg",
      "img1":"img/product-box_item14-1.jpg",
      "img2":"img/product-box_item14-2.jpg",
      "img3":"img/product-box_item14-3.jpg",
      "name":"ELLERY X M'O CAPSULE",
      "text":"Known for her sculptural takes on traditional tailoring, Australian arbiter of cool Kym Ellery teams up with Moda Operandi.",
      "textProduct":"Compellingly actualize fully researched processes before proactive outsourcing. Progressively syndicate collaborative architectures before cutting-edge services. Completely visualize parallel core competencies rather than exceptional portals.",
      "price":"52.00",
      "color":"Red",
      "size":"Xl",
      "quantity":"2",
      "gender":"WOMEN"
  },
  {"id":"115",
      "img":"img/product-box_item15.jpg",
      "img1":"img/product-box_item15-1.jpg",
      "img2":"img/product-box_item15-2.jpg",
      "img3":"img/product-box_item15-3.jpg",
      "name":"ELLERY X M'O CAPSULE",
      "text":"Known for her sculptural takes on traditional tailoring, Australian arbiter of cool Kym Ellery teams up with Moda Operandi.",
      "textProduct":"Compellingly actualize fully researched processes before proactive outsourcing. Progressively syndicate collaborative architectures before cutting-edge services. Completely visualize parallel core competencies rather than exceptional portals.",
      "price":"52.00",
      "color":"Red",
      "size":"Xl",
      "quantity":"2",
      "gender":"MEN"
  },
  {"id":"116",
      "img":"img/product-box_item16.jpg",
      "img1":"img/product-box_item16-1.jpg",
      "img2":"img/product-box_item16-2.jpg",
      "img3":"img/product-box_item16-3.jpg",
      "name":"ELLERY X M'O CAPSULE",
      "text":"Known for her sculptural takes on traditional tailoring, Australian arbiter of cool Kym Ellery teams up with Moda Operandi.",
      "textProduct":"Compellingly actualize fully researched processes before proactive outsourcing. Progressively syndicate collaborative architectures before cutting-edge services. Completely visualize parallel core competencies rather than exceptional portals.",
      "price":"52.00",
      "color":"Red",
      "size":"Xl",
      "quantity":"2",
      "gender":"MEN"
  },
  {"id":"117",
      "img":"img/product-box_item17.jpg",
      "img1":"img/product-box_item17-1.jpg",
      "img2":"img/product-box_item17-2.jpg",
      "img3":"img/product-box_item17-3.jpg",
      "name":"ELLERY X M'O CAPSULE",
      "text":"Known for her sculptural takes on traditional tailoring, Australian arbiter of cool Kym Ellery teams up with Moda Operandi.",
      "textProduct":"Compellingly actualize fully researched processes before proactive outsourcing. Progressively syndicate collaborative architectures before cutting-edge services. Completely visualize parallel core competencies rather than exceptional portals.",
      "price":"52.00",
      "color":"Red",
      "size":"Xl",
      "quantity":"2",
      "gender":"WOMEN"
  },
  {"id":"118",
      "img":"img/product-box_item18.jpg",
      "img1":"img/product-box_item18-1.jpg",
      "img2":"img/product-box_item18-2.jpg",
      "img3":"img/product-box_item18-3.jpg",
      "name":"ELLERY X M'O CAPSULE",
      "text":"Known for her sculptural takes on traditional tailoring, Australian arbiter of cool Kym Ellery teams up with Moda Operandi.",
      "textProduct":"Compellingly actualize fully researched processes before proactive outsourcing. Progressively syndicate collaborative architectures before cutting-edge services. Completely visualize parallel core competencies rather than exceptional portals.",
      "price":"52.00",
      "color":"Red",
      "size":"Xl",
      "quantity":"2",
      "gender":"WOMEN"
  },
  {"id":"119",
      "img":"img/product-box_item19.jpg",
      "img1":"img/product-box_item19-1.jpg",
      "img2":"img/product-box_item19-2.jpg",
      "img3":"img/product-box_item19-3.jpg",
      "name":"ELLERY X M'O CAPSULE",
      "text":"Known for her sculptural takes on traditional tailoring, Australian arbiter of cool Kym Ellery teams up with Moda Operandi.",
      "textProduct":"Compellingly actualize fully researched processes before proactive outsourcing. Progressively syndicate collaborative architectures before cutting-edge services. Completely visualize parallel core competencies rather than exceptional portals.",
      "price":"52.00",
      "color":"Red",
      "size":"Xl",
      "quantity":"2",
      "gender":"MEN"
  },
  {"id":"120",
      "img":"img/product-box_item20.jpg",
      "img1":"img/product-box_item20-1.jpg",
      "img2":"img/product-box_item20-2.jpg",
      "img3":"img/product-box_item20-3.jpg",
      "name":"ELLERY X M'O CAPSULE",
      "text":"Known for her sculptural takes on traditional tailoring, Australian arbiter of cool Kym Ellery teams up with Moda Operandi.",
      "textProduct":"Compellingly actualize fully researched processes before proactive outsourcing. Progressively syndicate collaborative architectures before cutting-edge services. Completely visualize parallel core competencies rather than exceptional portals.",
      "price":"52.00",
      "color":"Red",
      "size":"Xl",
      "quantity":"2",
      "gender":"MEN"
  },
  {"id":"121",
      "img":"img/product-box_item21.jpg",
      "img1":"img/product-box_item21-1.jpg",
      "img2":"img/product-box_item21-2.jpg",
      "img3":"img/product-box_item21-3.jpg",
      "name":"ELLERY X M'O CAPSULE",
      "text":"Known for her sculptural takes on traditional tailoring, Australian arbiter of cool Kym Ellery teams up with Moda Operandi.",
      "textProduct":"Compellingly actualize fully researched processes before proactive outsourcing. Progressively syndicate collaborative architectures before cutting-edge services. Completely visualize parallel core competencies rather than exceptional portals.",
      "price":"52.00",
      "color":"Red",
      "size":"Xl",
      "quantity":"2",
      "gender":"MEN"
  },
  {"id":"122",
      "img":"img/product-box_item22.jpg",
      "img1":"img/product-box_item22-1.jpg",
      "img2":"img/product-box_item22-2.jpg",
      "img3":"img/product-box_item22-3.jpg",
      "name":"ELLERY X M'O CAPSULE",
      "text":"Known for her sculptural takes on traditional tailoring, Australian arbiter of cool Kym Ellery teams up with Moda Operandi.",
      "textProduct":"Compellingly actualize fully researched processes before proactive outsourcing. Progressively syndicate collaborative architectures before cutting-edge services. Completely visualize parallel core competencies rather than exceptional portals.",
      "price":"52.00",
      "color":"Red",
      "size":"Xl",
      "quantity":"2",
      "gender":"MEN"
  },
  {"id":"123",
      "img":"img/product-box_item23.jpg",
      "img1":"img/product-box_item23-1.jpg",
      "img2":"img/product-box_item23-2.jpg",
      "img3":"img/product-box_item23-3.jpg",
      "name":"ELLERY X M'O CAPSULE",
      "text":"Known for her sculptural takes on traditional tailoring, Australian arbiter of cool Kym Ellery teams up with Moda Operandi.",
      "textProduct":"Compellingly actualize fully researched processes before proactive outsourcing. Progressively syndicate collaborative architectures before cutting-edge services. Completely visualize parallel core competencies rather than exceptional portals.",
      "price":"52.00",
      "color":"Red",
      "size":"Xl",
      "quantity":"2",
      "gender":"MEN"
  },
  {"id":"124",
      "img":"img/product-box_item24.jpg",
      "img1":"img/product-box_item24-1.jpg",
      "img2":"img/product-box_item24-2.jpg",
      "img3":"img/product-box_item24-3.jpg",
      "name":"ELLERY X M'O CAPSULE",
      "text":"Known for her sculptural takes on traditional tailoring, Australian arbiter of cool Kym Ellery teams up with Moda Operandi.",
      "textProduct":"Compellingly actualize fully researched processes before proactive outsourcing. Progressively syndicate collaborative architectures before cutting-edge services. Completely visualize parallel core competencies rather than exceptional portals.",
      "price":"52.00",
      "color":"Red",
      "size":"Xl",
      "quantity":"2",
      "gender":"MEN"
  }
]`;
